language: android
sudo: false
branches:
  only:
    - master
android:
  components:
    - build-tools-23.0.1
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23
script: ./gradlew ci
